# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_factories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedSecretFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=100, verbose_name='Secret key')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_factories.Factor', verbose_name='Factor')),
            ],
        ),
    ]
