# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 01:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'verbose_name': 'Password Setting',
                'verbose_name_plural': 'Password Settings',
            },
        ),
        migrations.RemoveField(
            model_name='sharedsecretfactor',
            name='factor',
        ),
        migrations.DeleteModel(
            name='SharedSecretFactor',
        ),
    ]
