# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_auto_20171121_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordsettings',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
