language: python
python: 3.5

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - DATABASE_URL="mysql://root:@localhost/test_watchdog_id"
    - DJANGO_SETTINGS_MODULE="config.settings.local"
    - secure: Jn0u3R9SBZU8bRCfDA3V2t1KnZeq/lg/QvNxjeMAj6/ojjoKIxEjcq4u3yZBdGVwNB2DftC87R20ODXj+p+gAuDDwnRHTgIP9MNH14Bce4U1BJAGutPDPZprOzGWhj85siiYuqqdTuDiXIfD5WJvb/6ZCloiBqxIR4iRwTPP9PkBKS4KpGQMs3pvs9XPmp2gmz5ZBbdltnYD5DaXTM74PyHy8nnXF0BDK+tQgIZMXfyEz/YWGy/iTw28iEMpec6gBvkoT0FRUAwtZaY44rozdD/c/IBSihYv6j1A7S0DaSP4Kd7AKWkW84MaUrzU6KsJOKJwxCyr2soJJ+eLygCAZdbdDf6fXecbZnTdM525NoAlz7yBZ5bGFc8IXOXXNns7bWvbEeG4bplRaJbADg1SRI5C0CB9WMcOIAjRqDG5aUXBZDtV/QsooUR2GgIogR7j5cGfOpb0+Eofjlpo+FbNB+HaaYfuIAEZoveWICLMw6mwTJysDKVw7fzpfhL5Zx4nZ/fM3V6Fwte9jh9qJqpRkWgfLPSjMOfuXtcqLxsnYebExj3PogNugwVvcIiGxWTXW/e7oi7WcAfLayKED2VbgyDXUtVI4+As5DsKDdMudF/5cDYqAEQ/8wGDRUwhB65ROS/hSO2s5HyGY/IWx7lyCTYngCAq4i6PHkt+d2pvy3o=
  matrix:
    - TOX_ENV=dj110-coveralls DATABASE_URL="mysql://root:@localhost/test_watchdog_id"
    - TOX_ENV=dj111-coveralls DATABASE_URL="mysql://root:@localhost/test_watchdog_id"
    - TOX_ENV=dj20-coveralls DATABASE_URL="mysql://root:@localhost/test_watchdog_id"
    - TOX_ENV=djmaster-coveralls DATABASE_URL="mysql://root:@localhost/test_watchdog_id"

    - TOX_ENV=dj110-coveralls DATABASE_URL="postgres://postgres:@localhost/test_watchdog_id"
    - TOX_ENV=dj111-coveralls DATABASE_URL="postgres://postgres:@localhost/test_watchdog_id"
    - TOX_ENV=dj20-coveralls DATABASE_URL="postgres://postgres:@localhost/test_watchdog_id"
    - TOX_ENV=djmaster-coveralls DATABASE_URL="postgres://postgres:@localhost/test_watchdog_id"

    - TOX_ENV=flake8

matrix:
  allow_failures:
    - env: TOX_ENV=djmaster-coveralls DATABASE_URL="mysql://root:@localhost/test_watchdog_id"
    - env: TOX_ENV=djmaster-coveralls DATABASE_URL="postgres://postgres:@localhost/test_watchdog_id"
    - env: TOX_ENV=flake8

install:
  - pip install -U pip wheel
  - pip install tox
script:
  - tox -e $TOX_ENV
