version: '2.1'

services:
  db:
    image: healthcheck/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: watchdog_id
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
     - .env
    environment:
     DATABASE_URL: mysql://root:example@db/watchdog_id
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
