# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otppassword',
            name='shared_secret',
            field=models.CharField(help_text='base32 secret', max_length=16),
        ),
    ]
