# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('totp', '0002_auto_20171127_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otppassword',
            name='device_name',
            field=models.CharField(max_length=25, verbose_name='Device name'),
        ),
        migrations.AlterField(
            model_name='otppassword',
            name='last_used',
            field=models.DateTimeField(blank=True, help_text='Time of last use of the token', null=True,
                                       verbose_name='Last used'),
        ),
        migrations.AlterField(
            model_name='otppassword',
            name='shared_secret',
            field=models.CharField(max_length=16, verbose_name='base32 secret'),
        ),
    ]
