# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 20:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='U2FToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('device_name', models.CharField(default='Standard token', max_length=15, verbose_name='Device name')),
                ('public_key', models.TextField(verbose_name='Public key')),
                ('key_handle', models.TextField(verbose_name='Key handle')),
                ('app_id', models.TextField(verbose_name='App ID')),
                ('last_used', models.DateTimeField(blank=True, help_text='Time of last use of the token', null=True, verbose_name='Last used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u2f_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
                'verbose_name': 'U2F token',
                'verbose_name_plural': 'U2F tokens',
            },
        ),
    ]
