# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog_u2f', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u2ftoken',
            name='app_id',
        ),
        migrations.RemoveField(
            model_name='u2ftoken',
            name='key_handle',
        ),
        migrations.RemoveField(
            model_name='u2ftoken',
            name='public_key',
        ),
        migrations.AddField(
            model_name='u2ftoken',
            name='device_data',
            field=models.TextField(default='', verbose_name='Authentication data'),
            preserve_default=False,
        ),
    ]
