# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yubico_otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yubicootpdevice',
            name='device_id',
            field=models.CharField(max_length=12, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='yubicootpdevice',
            name='device_name',
            field=models.CharField(default='Yubico Token', help_text='Affordable user name token', max_length=25, verbose_name='Device name'),
        ),
        migrations.AlterField(
            model_name='yubicootpdevice',
            name='last_used',
            field=models.DateTimeField(blank=True, help_text='Time of last use of the token', null=True, verbose_name='Last used'),
        ),
    ]
