# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_oidc', '0002_auto_20171210_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jwkey',
            name='user',
        ),
        migrations.AlterField(
            model_name='jwkey',
            name='kty',
            field=models.CharField(choices=[('RSA', 'RSA'), ('EC', 'Elliptic Curve'), ('oct', 'Octet sequence')], max_length=5, verbose_name='Key Types'),
        ),
    ]
