# Generated by Django 2.0 on 2017-12-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_local_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='event_type',
            field=models.CharField(max_length=150, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, verbose_name='Session ID'),
        ),
    ]
